Auth/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from Auth.forms import LoginForm, PasswordChange
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^signup/$', views.signup, name='auth_signup'),
    path('login/', auth_views.LoginView.as_view(template_name='Main/m_login.html',authentication_form=LoginForm, extra_context=({'title':'Login','Tab':'login'})), name = 'auth_login'),
    path('passwordChange/', auth_views.PasswordChangeView.as_view(template_name='Auth/passwordChange.html',form_class=PasswordChange, extra_context=({'title':'Change Password','Tab':'profile'})), name = 'auth_passwordChange'),
    path('passwordChangeDone/', auth_views.PasswordChangeDoneView.as_view(template_name='Auth/passwordChangeDone.html',extra_context=({'title':'Password Changed !','Tab':'profile'})), name = 'password_change_done'),
    path('logout/', auth_views.LogoutView.as_view(extra_context=({'title':'Logout','Tab':'logout'})), name = 'auth_logout'),
    path('Club/', views.updateClubProfile, name = 'auth_updateClubProfile'),
    path('Rotaractor/', views.updateUserProfile, name = 'auth_updateUserProfile'),
    url(r'^Rotaractors/view/(?P<username>\w+)/$', views.viewUserProfile, name='auth_viewUserProfile'),
    path('createCouncilAccounts/', views.createCouncilAccounts, name = 'auth_createCouncilAccounts'),
    path('createCouncilPosts/', views.createCouncilPosts, name = 'auth_createCouncilPosts'),
    path('createCouncilMaps/', views.createCouncilMaps, name = 'createCouncilMaps'),
]

RotarApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('district/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('SecReport.urls')),
    path('', include('Auth.urls')),
    path('', include('DistReport.urls')),
]


if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SecReport/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # path('migrateData/',views.migrate_data),
    # path('createMonths/',views.createMonths),
    # path('createPermissions/',views.createPermissions),
    # path('addMonth/',views.add_month),
    
    path('report/', views.present_report, name = 'secReport_presentReport'),
    path('secReport/', views.present_report1, name = 'secReport_presentReport1'),
    path('saveReport/', views.save_report, name = 'secReport_saveReport'),
    path('saveSecReport/', views.save_report1, name = 'secReport_saveReport1'),
    url(r'^finishReport/(?P<reportId>.+?)/$', views.finish_report, name='secReport_finishReport'),
    path('finishSecReport/', views.finish_report1, name='secReport_finishReport1'),
    path('submitSecReport/', views.submit_report1, name='secReport_submitReport1'),
    path('editSecReport/', views.edit_report1, name='secReport_editReport1'),
    url(r'^submitReport/(?P<reportId>.+?)/$', views.submit_report, name='secReport_submitReport'),
    url(r'^exportReport/(?P<reportId>.+?)/$', views.export_report, name='secReport_exportReport'),
    url(r'^viewReport/(?P<reportId>.+?)/$', views.view_report, name='secReport_viewReport'),
    url(r'^mailReport/(?P<reportId>.+?)/$', views.email_report, name='secReport_emailReport'),
    path('fetchReports/', views.fetch_reports, name = 'secReport_fetchReports'),

    # Admin panel
    path('secReport/manageAccess/', views.manageAccess, name = 'secReport_manageAccess'),
    path('secReport/responses/', views.responses, name = 'secReport_responses'),
    path('secReport/getPermissions/', views.getPermissions, name = 'secReport_getPermissions'),
    path('secReport/changePermission/', views.changePermission, name = 'secReport_changePermission'),
    

]

SecReport/models.py
from django.db import models
from Auth.models import Account, Club
import uuid
from datetime import datetime

months = (
    ("01","January"),
    ("02","February"),
    ("03","March"),
    ("04","April"),
    ("05","May"),
    ("06","June"),
    ("07","July"),
    ("08","August"),
    ("09","September"),
    ("10","October"),
    ("11","November"),
    ("12","December")
)

class Month(models.Model) :
    month = models.CharField(blank = True, max_length=2, choices = months, verbose_name = "Month")
    year = models.CharField(blank = True, max_length=4, verbose_name = "Year")

    class Meta:
        verbose_name = 'Month'
        verbose_name_plural = 'Months'

    def __str__(self):
        return f'{self.month}-{self.year}'

class ReportAccess(models.Model) :
    club = models.ForeignKey(Club, on_delete = models.CASCADE, null = True, blank = True)
    month = models.ForeignKey(Month, on_delete = models.CASCADE, null = True, blank = True)
    edit = models.BooleanField(verbose_name = "Edit permission", default = False, null = True, blank = True)
    view = models.BooleanField(verbose_name = "View permission", default = True, null = True, blank = True)

    class Meta:
        verbose_name = 'Permission'
        verbose_name_plural = 'Permissions'

    def __str__(self):
        return f'{self.club.login.username}-{self.month.month}-{self.month.year}'


class DuesPaid(models.Model) :
    club = models.ForeignKey(Club, on_delete = models.CASCADE, null = True, blank = True)
    dues = models.IntegerField(blank = True, null = True, default = 0, verbose_name="Total Dues Paid")

    class Meta:
        verbose_name = 'Dues Paid'
        verbose_name_plural = 'Dues Paid'

    def __str__(self):
        return f'{self.club.clubName}-{self.dues}'

class Report(models.Model):
    reportId = models.CharField(blank = True, max_length=32, verbose_name = "Report Id", primary_key = True)
    reportingClub = models.ForeignKey(Club, on_delete = models.CASCADE, null = True, blank = True)
    month = models.ForeignKey(Month, on_delete = models.CASCADE, null = True, blank = True, default = None)
    reportingMonth = models.CharField(blank = True, max_length=2, choices = months, verbose_name = "Month")
    reportingDate = models.DateTimeField(verbose_name = "Reported on", default=datetime.now, null = True, blank = True)
    duesPaidAlready = models.CharField(blank = True, max_length=6, verbose_name = "District Dues paid upto the last month")
    duesPaidInThisMonth = models.CharField(blank = True, max_length=6,verbose_name = "District Dues paid in this month")
    suggestions = models.TextField(blank = True, max_length=1000,verbose_name = "Suggestions", default="")
    status = models.CharField(blank = True, max_length = 2, verbose_name = "Report Status", choices = (("0","Incomplete"),("1","Complete"),('2',"Partially Complete")), default = "0")
    class Meta:
        verbose_name = 'Report'
        verbose_name_plural = 'Reports'

    def __str__(self):
        return f'{self.reportingClub.clubName}-{self.reportingMonth}'

class MemberMatrixAttribute(models.Model):
    attribute = models.CharField(blank = True, max_length = 40, verbose_name = "Members Matrix Attribute")
    operation = models.CharField(blank = True, max_length=2, verbose_name ="Operation", default='')
    attributeStatus = models.BooleanField(verbose_name = "Status", default = True, null = True, blank = True)

    class Meta:
        verbose_name = 'MemberMatrixAttribute'
        verbose_name_plural = 'MemberMatrixAttributes'

    def __str__(self):
        return f'{self.attribute}'

class MemberMatrix(models.Model) :
    memberMatrixId = models.AutoField(primary_key=True)
    reportId = models.ForeignKey(Report, on_delete=models.CASCADE)
    attribute = models.ForeignKey(MemberMatrixAttribute, on_delete = models.CASCADE, null = True, blank = True)
    maleCount = models.CharField(blank = True, max_length=4,verbose_name = "Male Count")
    femaleCount = models.CharField(blank = True, max_length=4,verbose_name = "Female Count")
    othersCount = models.CharField(blank = True, max_length=4,verbose_name = "Others Count")

    class Meta:
        verbose_name = 'Member Matrix Row'
        verbose_name_plural = 'Member Matrix rows'

    def __str__(self):
        return f'{self.reportId.reportingClub.clubName}-{self.reportId.reportingMonth}-{self.attribute}'

class FeedbackQuestion(models.Model) :
    questionText = models.CharField(blank = True, max_length = 100, verbose_name = "Question Text")
    questionStatus = models.BooleanField(verbose_name = "Status", default = True, null = True, blank = True)

    class Meta:
        verbose_name = 'FeedbackQuestion'
        verbose_name_plural = 'FeedbackQuestions'

    def __str__(self):
        return f'{self.questionText}'

class Feedback(models.Model) :
    feedbackId = models.AutoField(primary_key=True)
    reportId = models.ForeignKey(Report, on_delete=models.CASCADE)
    feedbackQuestion = models.ForeignKey(FeedbackQuestion, on_delete = models.CASCADE, null = True, blank = True)
    booleanResponse = models.BooleanField(verbose_name = "Feedback Response", null = True, blank = True)

    class Meta:
        verbose_name = 'Feedback'
        verbose_name_plural = 'Feedbacks'

    def __str__(self):
        return f'{self.reportId.reportingClub.clubName}-{self.reportId.reportingMonth}-{self.feedbackQuestion.id}'

class Meeting(models.Model) :
    meetingId = models.CharField(max_length=32, verbose_name = "Meeting Id", primary_key = True)
    hostClub = models.ForeignKey(Club, on_delete = models.CASCADE, null = True, blank = True, related_name = 'meeting')
    meetingNo = models.CharField(blank = True, verbose_name = "Meeting Number", default="", max_length = 3)
    meetingDate = models.DateTimeField(verbose_name = "Date", default=None, null = True, blank = True)
    meetingAgenda = models.CharField(blank = True, max_length=1000,verbose_name = "Agenda")
    bylawsBoolean = models.BooleanField(verbose_name="Bylaws passed?", null = True, blank = True)
    budgetBoolean = models.BooleanField(verbose_name="Budget passed?", null = True, blank = True)
    meetingAttendance = models.CharField(blank = True, max_length=5,verbose_name = "Attendance")
    meetingType = models.CharField(blank = True, max_length = 2, verbose_name = "Meeting Type", choices = (("1","BOD"),("2","GBM")))
    jointBoolean = models.BooleanField(default = False, verbose_name="is Joint?")

    class Meta:
        verbose_name = 'Meeting'
        verbose_name_plural = 'Meetings'

    def __str__(self):
        return f'{self.hostClub.clubName}-{self.meetingType}-{self.meetingDate.strftime("%d-%B")}' if self.meetingDate!=None else f'{self.hostClub.clubName}-{self.meetingType}'

class Event(models.Model):
    eventId = models.CharField(blank = True, max_length=32, verbose_name = "Event Id", primary_key = True)
    hostClub = models.ForeignKey(Club, on_delete = models.CASCADE, null = True, blank = True, related_name = 'event')
    eventStartDate = models.DateTimeField(verbose_name = "Start Date", null = True, blank = True)
    eventEndDate = models.DateTimeField(verbose_name = "End Date", null = True, blank = True)
    eventName = models.CharField(blank = True, max_length=50,verbose_name = "Name")
    eventAvenue = models.CharField(blank = True, max_length=5,verbose_name = "Avenue")
    eventAttendance = models.CharField(blank = True, max_length=6,verbose_name = "Attendance")
    eventHours = models.CharField(blank = True, max_length=6,verbose_name = "Volunteer Hours")
    eventFundRaised = models.CharField(blank = True, max_length=8,verbose_name = "Funds Raised")
    eventDescription = models.CharField(blank = True, max_length=1000,verbose_name = "Description")
    eventLink = models.CharField(blank = True, max_length=150,verbose_name = "Instagram Link")
    eventType = models.CharField(blank = True, max_length=2, verbose_name = "Event type", choices = (("1","Completed"),("2","Future Event")))
    jointBoolean = models.BooleanField(default = False, verbose_name="is Joint?")

    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Events'

    def __str__(self):
        return f'{self.eventName}-{self.hostClub.clubName}'
    
class Bulletin(models.Model) :
    bulletinId = models.CharField(blank = True, max_length=32, verbose_name = "Bulletin Id", primary_key = True)
    hostClub = models.ForeignKey(Club, on_delete = models.CASCADE, null = True, blank = True, related_name = 'Bulletin')
    bulletinName = models.CharField(blank = True, max_length=50,verbose_name = "Name of Bulletin")
    bulletinType = models.CharField(blank = True, max_length=10,verbose_name = "Type of Bulletin")
    bulletinLink = models.CharField(blank = True, max_length=150,verbose_name = "Link")
    bulletinIssuedOn = models.DateTimeField(verbose_name = "Issued on", null = True, blank = True)
    lastBulletinIssuedOn = models.DateTimeField(verbose_name = "Last Issued on", null = True, blank = True)
    bulletinFrequency = models.CharField(blank = True, max_length=20,verbose_name = "Frequency")
    jointBoolean = models.BooleanField(default = False, verbose_name="is Joint?")
    
    class Meta:
        verbose_name = 'Bulletin'
        verbose_name_plural = 'Bulletins'

    def __str__(self):
        return f'{self.bulletinId}-{self.hostClub.clubName}'

class ReportBulletinMapping(models.Model) :
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    bulletin = models.ForeignKey(Bulletin, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.bulletin.bulletinId}'

class ReportEventMapping(models.Model) :
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.report.reportingClub.clubName}-{self.report.reportingMonth}-{self.event.eventName}'

class ReportMeetingMapping(models.Model) :

SecReport/templates/SecReport/admin.html
<div class="heading">
    <b>General Body Meeting</b>
</div>
<br>
<div class="container-fluid table-responsive">

    <div id="generalBodyMeetings">

    </div>
    <button type="button" class="addRow" onclick="appendGeneralBodyMeeting()">Add Row</button>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">

</div>
<br>
<div class="heading">
    <b>BOD Meeting</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="boardOfDirectorsMeetings">
        
    </div>
    <button type="button" class="addRow" onclick="appendBODMeeting()">Add Row</button>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>
<br>
<div class="heading">
    <b>Club Membership Details</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="text-center mobile m-subHeading">
        Member-Matrix
        <br>
        <p style="font-size:2.2vw;color:#337ab7">{ 1 : Intial Count, 2 : Added this month, 3 : Left, 4 : Prospective, 5 : Guest, T : Total }<br>
        <br>
    </div>
    <div class ="m-memberMatrix" id="memberMatrix">

    </div>
    <div class ="m-memberMatrix" id="memberMatrixTotal">

    </div>
    <hr>
</div>
<br>
<div class="heading">
    <b>Dues paid to District</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="row" id="dues">
        <div class="col-lg-6">
            <p class="label" id="duesLabel01">Total number of members at the <br>beginning of this month (N)</p><br>
            <input tab="Admin" type="text" id="totalNumberOfMembers" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label" id="duesLabel02">Number of members inducted <br>in this month (n)</p><br>
            <input tab="Admin" type="text" id="totalNumberOfAddedMembers" readonly>
          </div>
          <div class="col-lg-6">
          <p class="label">Dues paid upto the last month <br>@ INR 300
            Per member (P)<b style="color:red"></b>
            </p><br>
          <input tab="Admin" type="text" id="paidAlready" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label" id="duesLabel03">District dues paid in this month<b style="color:red"> *</b><br>(p)</p><br>
            <input tab="Admin" type="number" min=0 step=1 oninput="validity.valid||(value='');updateList(this.id,null,null);updatePending(this.value);" name="duesPaidInThisMonth" id="duesPaidInThisMonth">
          </div>
          <div class="col-lg-6">
            <p class="label">The fees amount that the district<br>owes : (N + n) * 300</p><br>
            <input tab="Admin" type="text" id="owed" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label">Pending dues<br>(N + n) * 300 - (P + p)</p>
            <input tab="Admin" type="text" id="pending" readonly>
          </div>
    </div>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div> 

<div class="container" id="reportButtons" style="padding-bottom:0;min-width:100%;">
  <div class="row" style="width:100%;margin:0">
      <div class="col-4">
          <button type="button" id="reportButton00" onclick="openSection()" disabled>Previous</button>
      </div>
      <div class="col-4">
          <button type="button" id="reportButton01" onclick="save()">Save<span id="loader" style="display:none">&nbsp;&nbsp;<i class="fa fa-circle-o-notch fa-spin"></i></span></button>
      </div>
      <div class="col-4">
          <button type="button" id="reportButton02" onclick="openSection('Avenue')">Next</button>
      </div>
  </div>
  <br class="mobile">
  <div class="row" style="width:100%;margin:0;padding:0">
      <div class="col-4">
      
      </div>
      <div class="col-lg-4 col-xs-12" id="submitButton">
          <!-- <button class="addRow" id="submit3" type="button" onclick="customSubmit()" style="float:right;width:100%">Finish</button> -->
      </div>
      <div class="col-4">
          
      </div>
  </div>
</div>

SecReport/templates/SecReport/adminM.html
<div class="heading">
    <b>General Body Meeting</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="generalBodyMeetings">

    </div>
</div>
<br>
<div class="heading">
    <b>BOD Meeting</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="boardOfDirectorsMeetings">
        
    </div>
</div>
<br>
<div class="heading">
    <b>Club Membership Details</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="text-center mobile m-subHeading">
        Member-Matrix
        <br>
        <p style="font-size:2.2vw;color:#337ab7">{ 1 : Intial Count, 2 : Added this month, 3 : Left, 4 : Prospective, 5 : Guest, T : Total }<br>
        <br>
    </div>
    <div class ="m-memberMatrix" id="memberMatrix">

    </div>
    <div class ="m-memberMatrix" id="memberMatrixTotal">

    </div>
    <hr>
</div>
<br>
<div class="heading">
    <b>Dues paid to District</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="row">
        <div class="col-lg-6">
            <p class="label" id="duesLabel01">Total number of members at the <br>beginning of this month (N)</p><br>
            <input tab="Admin" type="text" id="totalNumberOfMembers" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label" id="duesLabel02">Number of members inducted <br>in this month (n)</p><br>
            <input tab="Admin" type="text" id="totalNumberOfAddedMembers" readonly>
          </div>
          <div class="col-lg-6">
          <p class="label">Dues paid upto the last month <br>@ INR 300
            Per member (P)
            </p><br>
          <input tab="Admin" type="text" id="paidAlready" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label" id="duesLabel03">District dues paid in this month<br>(p)</p><br>
            <input tab="Admin" type="number" min=0 step=1 oninput="validity.valid||(value='');updateList(this.id,null,null);updatePending(this.value);" name="duesPaidInThisMonth" id="duesPaidInThisMonth">
          </div>
          <div class="col-lg-6">
            <p class="label">The fees amount that the district<br>owes : (N + n) * 300</p><br>
            <input tab="Admin" type="text" id="owed" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label">Pending dues<br>(N + n) * 300 - (P + p)</p>
            <input tab="Admin" type="text" id="pending" readonly>
          </div>
    </div>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>

SecReport/templates/SecReport/adminView.html
<div class="heading">
    <b>General Body Meeting</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="generalBodyMeetings">

    </div>
</div>
<br>
<div class="heading">
    <b>BOD Meeting</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="boardOfDirectorsMeetings">
        
    </div>
</div>
<br>
<div class="heading">
    <b>Club Membership Details</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="text-center mobile m-subHeading">
        Member-Matrix
        <br>
        <p style="font-size:2.2vw;color:#337ab7">{ 1 : Intial Count, 2 : Added this month, 3 : Left, 4 : Prospective, 5 : Guest, T : Total }<br>
        <br>
    </div>
    <div class ="m-memberMatrix" id="memberMatrix">

    </div>
    <div class ="m-memberMatrix" id="memberMatrixTotal">

    </div>
    <hr>
</div>
<br>
<div class="heading">
    <b>Dues paid to District</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="row">
        <div class="col-lg-6">
            <p class="label" id="duesLabel01">Total number of members at the <br>beginning of this month (N)</p><br>
            <input tab="Admin" type="text" id="totalNumberOfMembers" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label" id="duesLabel02">Number of members inducted <br>in this month (n)</p><br>
            <input tab="Admin" type="text" id="totalNumberOfAddedMembers" readonly>
          </div>
          <div class="col-lg-6">
          <p class="label">Dues paid upto the last month <br>@ INR 300
            Per member (P)
            </p><br>
          <input tab="Admin" type="text" id="paidAlready" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label" id="duesLabel03">District dues paid in this month<br>(p)</p><br>
            <input tab="Admin" type="number" min=0 step=1 oninput="validity.valid||(value='');updateList(this.id,null,null);updatePending(this.value);" name="duesPaidInThisMonth" id="duesPaidInThisMonth">
          </div>
          <div class="col-lg-6">
            <p class="label">The fees amount that the district<br>owes : (N + n) * 300</p><br>
            <input tab="Admin" type="text" id="owed" readonly>
          </div>
          <div class="col-lg-6">
            <p class="label">Pending dues<br>(N + n) * 300 - (P + p)</p>
            <input tab="Admin" type="text" id="pending" readonly>
          </div>
    </div>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>

SecReport/templates/SecReport/avenue.html
<div class="heading">
    <b>Events Carried Out</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="instructions" style="padding:2%;color:#337ab7;">
        <h6><b>In the 'Instagram Link' field, you have to copy and paste the link.</b></h6>
        <h6><b>Type '-' in case you don't have one.</b></h6>
        <hr>
    </div>
    
    <div id="events">

    </div>
    <button type="button" class="addRow" onclick="appendEvent()">Add Row</button>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>

<div class="container" id="reportButtons" style="padding-bottom:0;min-width:100%;">
    <div class="row" style="width:100%;margin:0">
        <div class="col-4">
            <button type="button" id="reportButton20" onclick="openSection('Admin')">Previous</button>
        </div>
        <div class="col-4">
            <button type="button" id="reportButton21" onclick="save()">Save<span id="loader" style="display:none">&nbsp;&nbsp;<i class="fa fa-circle-o-notch fa-spin"></i></span></button>
        </div>
        <div class="col-4">
            <button type="button" id="reportButton22" onclick="openSection('Others')">Next</button>
        </div>
    </div>
    <br class="mobile">
    <div class="row" style="width:100%;margin:0;padding:0">
        <div class="col-4">
        
        </div>
        <div class="col-lg-4 col-xs-12" id="submitButton">
            <!-- <button class="addRow" id="submit3" type="button" onclick="customSubmit()" style="float:right;width:100%">Finish</button> -->
        </div>
        <div class="col-4">
            
        </div>
    </div>
  </div>
  

SecReport/templates/SecReport/avenueM.html
<div class="heading">
    <b>Events Carried Out</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="events">

    </div>
</div>

SecReport/templates/SecReport/othersM.html
<div class="heading">
    <b>Details of Bulletin</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="bulletins">
        
    </div>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>
<br>
<div class="heading">
    <b>Upcoming Events</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div id="futureEvents">

    </div>
</div>
<br>
<div class="heading">
    <b>Feedback</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="row" id = "feedback">
    </div>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>
<br>
<div class="heading">
    <b>Suggestions (If any)</b>
</div>
<br>
<div class="container-fluid table-responsive">
    <div class="row">
        <textarea tab="Others" oninput="updateList(this.id,null,null)" maxlength="100" rows="5" name="suggestions"  id="suggestion00"></textarea>
    </div>
    <hr style="border-width: medium;border-color:#337ab7;border-radius : 4px;">
</div>

SecReport/templates/SecReport/reportList.html
{% extends "Main/base.html" %}
    
{% load static %}

{% block content %}
<div class="listrow" id="listSection">
    <div class="container-fluid">
        <h4 id="reportHeading1" class="text-center"><b>Club wise Secretarial Reports</b></h4>
        <br>
        <hr class="mb-4 mt-8" style="margin:auto;border-width: medium;border-color: #D41367;width:95%">
        {% for Club in Clubs %}
        {% with count=Club.report_set.count latest=Club.report_set.all.latest.month %}

        <div class="row">
            <div class="col-lg-6">
                <img id="clublogo" src="{{STATIC_URL}}{{ Club.club.logo.url }}" alt="Rotaract" width="30" height="30"><b style="color:#337ab7">{{ Club.name }}</b>
            </div>
            <div class="col-lg-2">
                <b style="color:#337ab7">Count : </b>{{ count }}
            </div>
            <div class="col-lg-2">
                {% if latest %}
                <b style="color:#337ab7">Last : </b>{{ latest }}
                {% else %}
                <b style="color:#337ab7">Last : </b>NA
                {% endif %}
            </div>
            <div class="col-lg-2">
                <button type="button" id="member" onclick="window.location.href = `{% url 'listReports' username=Club.username %}`;" style="color:white" class="text-center" >View Reports</button>
                
            </div>
        </div>
    
        {% endwith %}
        {% endfor %}
    <br><br>
    </div>
</div>

{% endblock content%}