Auth/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from Auth.forms import LoginForm, PasswordChange
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^signup/$', views.signup, name='auth_signup'),
    path('login/', auth_views.LoginView.as_view(template_name='Main/m_login.html',authentication_form=LoginForm, extra_context=({'title':'Login','Tab':'login'})), name = 'auth_login'),
    path('passwordChange/', auth_views.PasswordChangeView.as_view(template_name='Auth/passwordChange.html',form_class=PasswordChange, extra_context=({'title':'Change Password','Tab':'profile'})), name = 'auth_passwordChange'),
    path('passwordChangeDone/', auth_views.PasswordChangeDoneView.as_view(template_name='Auth/passwordChangeDone.html',extra_context=({'title':'Password Changed !','Tab':'profile'})), name = 'password_change_done'),
    path('logout/', auth_views.LogoutView.as_view(extra_context=({'title':'Logout','Tab':'logout'})), name = 'auth_logout'),
    path('Club/', views.updateClubProfile, name = 'auth_updateClubProfile'),
    path('Rotaractor/', views.updateUserProfile, name = 'auth_updateUserProfile'),
    url(r'^Rotaractors/view/(?P<username>\w+)/$', views.viewUserProfile, name='auth_viewUserProfile'),
    path('createCouncilAccounts/', views.createCouncilAccounts, name = 'auth_createCouncilAccounts'),
    path('createCouncilPosts/', views.createCouncilPosts, name = 'auth_createCouncilPosts'),
    path('createCouncilMaps/', views.createCouncilMaps, name = 'createCouncilMaps'),
]

Main/urls.py
from django.urls import path, include
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('', views.home1, name = 'main_home'),
    path('home/', views.home1, name = 'main_home1'),
    path('aboutUs/', views.aboutUs, name = 'main_aboutUs'),
    path('eRyla/', views.eRyla, name = 'main_eRyla'),
    path('council/', views.council, name = 'main_council'),
    url(r'^whatWeDo/(?P<avenue>.+?)/$', views.whatWeDo, name='main_whatWeDo'),
    path('whatWeDo/test/', views.testWhatWeDo, name='main_testWhatWeDo'),
    path('whatWeDo/', views.whatWeDo, name='main_whatWeDo'),
    url(r'^whatWeDo/test/(?P<eventId>.+?)/$', views.testWhatWeDo, name='main_testWhatWeDo'),
    path('resources/', views.resources, name = 'main_resources'),
    url(r'^document/(?P<document>.+?)/$', views.document, name='main_document'),
    path('zones/', views.zone, name = 'main_zones'),

       
]

RotarApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('district/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('SecReport.urls')),
    path('', include('Auth.urls')),
    path('', include('DistReport.urls')),
]


if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/models.py
from django.db import models

class FAQ(models.Model):
    question = models.CharField(blank = True, max_length=100,verbose_name = "Question")
    answer = models.CharField(blank = True, max_length=1000,verbose_name = "Answer")

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'

    def __str__(self):
        return f'{self.question}'

avenues = {
    "1":"Professional Development",
    "2":"Club Service",
    "3":"International Service",
    "4":"Community Service",
    "5":"Foundation",
    "6":"Financial Service",
    "7":"Public Image",
}

class WhatWeDo(models.Model):
    eventNo = models.CharField(verbose_name = "Serial Number", max_length = 2, default = "99")
    eventName = models.CharField(verbose_name = "Name", max_length = 50)
    eventDescription = models.TextField(verbose_name = "Event Description")
    eventCategory = models.CharField(verbose_name = "Avenue", choices = avenues.items(), max_length = 2, default="0")
    eventInstagramPost = models.TextField(verbose_name = "Instagram Post")
    eventVisibility = models.BooleanField(verbose_name = "Status", default = True)

    class Meta:
        verbose_name = 'WhatWeDo'
        verbose_name_plural = 'WhatWeDos'

    def __str__(self):
        return f'{self.eventName}'

Main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from Auth.models import DistrictCouncil, Club
from Main.models import WhatWeDo, avenues
from django.http import HttpResponseNotFound

# Create your views here.

def home(request):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/home.html',{'Tab':'home','DRole':dRole})

def home1(request):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/m_home.html',{'Tab':'home','DRole':dRole})

def aboutUs(request):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/m_aboutUs.html',{'Tab':'aboutUs','DRole':dRole})

def eRyla(request):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/m_eRyla.html',{'Tab':'aboutUs','DRole':dRole})

def council(request):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/m_council.html',{'Tab':'council','DRole':dRole})

def whatWeDo(request, avenue = "0"):
    if avenue not in avenues.keys() :
        return HttpResponseNotFound("Page not found") 
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    events = WhatWeDo.objects.filter(eventCategory=str(avenue)).all()
    return render(request, 'Main/m_whatWeDo.html',{'Tab':'whatWeDo','SubTab':avenues[str(avenue)].replace(" ",''),'Header':avenues[str(avenue)],'DRole':dRole,'events':events})

def testWhatWeDo(request, eventId=-1):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    events = WhatWeDo.objects.filter(id=eventId).all() if int(eventId)>=0 else WhatWeDo.objects.all()
    return render(request, 'Main/m_testWhatWeDo.html',{'Tab':'whatWeDo','DRole':dRole,'events':events})

def resources(request):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/m_resources.html',{'Tab':'resources','DRole':dRole,'document':document})

def document(request,document):
    dRole = None
    if request.user.is_authenticated :
        dRole = DistrictCouncil.objects.filter(accountId = request.user).first()
        dRole = dRole.districtRole.distRoleId if dRole!=None else None
    return render(request, 'Main/m_document.html',{'DRole':dRole,'document':document})

def zone(request):
    clubObjects = Club.objects.all()
    clubs = dict()
    zones = dict()    
    for club in clubObjects :
        if(club.zone and club.rotaryId and club.clubName!="") :
            clubs[club.rotaryId] = {
                    "clubId":club.rotaryId,
                    "clubLogo":club.clubLogo,
                    "clubName":club.clubName,
                    "charterDate":club.charterDate,
                    "about": club.clubName+"\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
                }
            if(club.zone) not in zones :
                zones[club.zone] = dict()    
            zones[club.zone][club.clubName] = {
                "clubId":club.rotaryId,
                "clubLogo":club.clubLogo,
                "clubName":club.clubName,
            }

    zones = [(k, v) for k, v in zones.items()] 
    zones = [tuple(zones[i:i+2]) for i in range(0, len(zones), 2)]

    return render(request, 'Main/m_zones.html',{'zones':zones,'clubs':clubs,'Tab':'zones'})

def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

Main/templates/Main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta name="google-site-verification" content="iMTaFl6E5zCIsxlp0ocqGVKPqsKX8585i4pb44LPghE" />
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content='width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;' name='viewport' />
    <meta name="theme-color" content="#D41367"/>
    <link rel="icon" href="{% static 'Main/images/district_logo.png' %}" type="image/icon type">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <!-- External javascript file, that does everything needed for this webApp -->

    <!-- External css files -->
    <link rel="stylesheet" href="{% static 'Main/css/main-d.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/main-m.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/navigation-d.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/navigation-m.css' %}">

    <link rel="stylesheet" href="{% static 'Main/css/report-2-d.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/report-2-m.css' %}">

    <link rel="stylesheet" href="{% static 'Main/css/tasks-d.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/tasks-m.css' %}">

    <link rel="stylesheet" href="{% static 'Auth/css/login-d.css' %}">
    <link rel="stylesheet" href="{% static 'Auth/css/login-m.css' %}">


    {% if Title %}
        <title>Rotaract D3131 -  {{ Title }}</title>
    {% else %}
        <title>Rotaract District 3131</title>
    {% endif %}

  </head>

  <body>

    {% include "Main/navbar.html" %}

    <div class="container" id="mainWrapperContainer" style="border:none">
      {% block content %}{% endblock %}
    </div>
    <br class="mobile">
    <br class="mobile">

    {% if not Title %}
      <!-- {% include "Main/footer.html" %} -->
    {% endif %}
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <script>

  function openNav() {
      let x = document.getElementById("mynavigation");
      if (x.className === "navigation sticky")
      {
          x.className += " responsive";
      }
      else
      {
          x.className = "navigation sticky";
      }
      x = document.getElementById("mainWrapperContainer");
      if (x.className === "container")
      {
          x.className += " blur";
      }
      else
      {
          x.className = "container";
      }
  }

  </script>

  {% block javascript %}{% endblock %}
</html>

Main/templates/Main/footer.html
<div class="footer">
    Designed and developed by,
    <br>District Website Team.
    <br>(Rtr. Saurabh Satavalekar, Rtr. Prathamesh Patil & Rtr. Madhu Pimprikar)
</div>

Main/templates/Main/m_aboutUs.html
{% extends "Main/m_base.html" %}

{% load static %}
{% block content %}
{% include "Main/m_headerSection.html" with text="About Us" %}
<div id="aboutUs">
<section class="section">
    <div class="container">
        <h3 class="center-align section-header">ABOUT ROTARY</h3>
        <hr class="hide-on-med-and-up">
        <br class="show-on-med-and-up">
        <div class="row flex">
            <div class="col l3 m12 s12 valign-wrapper">
                <img class="center-align section-image" src="{% static 'Main/images/download.png' %}" alt="Rotaract">
            </div>
            <div class="col l9 m12 s12 section-text">
                Rotary International is a universal network of 1.2 million acquaintances, companions, leaders, and problem-solvers who have a vision of the world where people unite and take action to create a long-lasting change – across the globe, in our communities, and ourselves.
                <br><br>Rotary is a 110-year-old international chain of clubs consisting of phenomenal visionaries who, since the establishment of this chain have used their passion, energy and, intelligence to contribute to the development of a sustainable world. 
                <br><br>The mission of Rotary is to provide service to others, promote integrity, and advance world understanding, goodwill, and peace through our fellowship of business, professional, and community leaders. Whereas, the far-sighted vision of Rotary sees a world where people unite and take action to create lasting change — across the globe, in our communities, and in ourselves.
            </div>
        </div>
    </div>
    <br>
    <!-- <hr class="hide-on-med-and-down" style="width:85%;border-width: 1px;border-color: black;background-color: black;"> -->
    <br>
    <section class="black valign-wrapper divider-section">
        <h5 class="white-text center-align" style="margin:auto;min-height:5vh"></h5>
    </section>
    <br>
    <div class="container">
        <h3 class="center-align section-header">ABOUT ROTARACT</h3>
        <hr class="hide-on-med-and-up">
        <br class="show-on-med-and-up">
        <div class="row flex">
            <div class="col l3 m12 s12 valign-wrapper">
                <img class="center-align section-image" src="{% static 'Main/images/rotaract.png' %}" alt="Rotaract">
            </div>
            <div class="col l9 m12 s12 section-text">
                Rotaract is a faction of young leaders who are developing innovative solutions to some of the world's greatest problems. Rotaract is primarily a global not-for-profit institution that holistically caters to personal and professional development needs with an extensive network across the globe, as well as largely setting sights on community service with our perennial belief in being service to others.
                <br><br>Rotaract Clubs works mainly under the standing committees of Professional Development, Club Service, International Service, Community Service, Foundation, and Financial Service.
                <br><br>If we were to talk about the statistics, then there are presently 203,298 Rotaractors who are part of 10,698 Rotaract Clubs across 180+ countries contributing to annihilating world problems with sustainable solutions.
                <br><br>We are an ever-expanding movement always welcoming new and enthusiastic members.
            </div>
        </div>
    </div>
</section>

<!-- <section class="section black">
    <div class="container">
        <h3 class="center-align white-text" class="section-header">ABOUT ROTARACT 3131</h3>
        <hr class="hide-on-med-and-up">
        <br class="show-on-med-and-up">
        <div class="row flex white-text">
            <div class="col l3 s12 valign-wrapper">
                <img class="center-align section-image" src="{% static 'Main/images/district_logo.png' %}" alt="Rotaract">
            </div>
            <div class="col l9 s12 section-text">
                Rotaract District 3131 is a non- profit organization striving to bring a change in the world by working in various distinctive standing committees along with Rotary International District 3131. (referred to as RID 3131)  It functions directly under the guidance of Rotary International. 
                <br><br>Rotaract District 3131 emerged at the beginning of Rotary International Year (abbreviated as RIY) 2008 - 09 when RID 3130 was bifurcated into two separate districts. Upon the formation of the district, the Rotary and Rotaract organization was given the charge of areas under of Raigad and Pune districts.
                <br><br>Rotaractors belong to an age group of above18 years (no age limit) and primarily work in the standing committees of Professional Development, Club Service, International Services, Community Service, Foundation, and Finance Services. Presently, 80+ Rotaract clubs are functioning cooperatively in RID 3131.
                <br><br>Rotaractors believe in relishing the work in which they invest their time. We Rotaractors of RID 3131 want to contribute to this world and make it a sustainable place to live for the upcoming generations. 
                <br><br>With a phenomenal history in the above-stated avenues and a vast network, we Rotaractors want to make a statement out there through our Rotaract Movement by Excelling and Growing Through Opportunities Together.
            </div>
        </div>
    </div>
    <br>
    <br>
</section> -->
<br>
<br>
{% comment %} <section class="section">
    <div class="container">
        <div class="row flex">
            <div class="col l3 s12 card-wrapper">
                <div class="card z-depth-3" style="background-color: #D41367;">
                    <h5 class="center-align white-text card-header">
                        Clubs
                    </h5>
                    <hr>
                    <h1 class="white-text center-align card-number">91</h1>
                </div>
            </div>
            <div class="col l3 s12 card-wrapper">
                <div class="card z-depth-3" style="background-color: #D41367;">
                    <h5 class="center-align white-text card-header">
                        Rotaractors
                    </h5>
                    <hr>
                    <h1 class="white-text center-align card-number">2153</h1>
                </div>
            </div>
            <div class="col l3 s12 card-wrapper">
                <div class="card z-depth-3" style="background-color: #D41367;">
                    <h5 class="center-align white-text card-header">
                        Projects
                    </h5>
                    <hr>
                    <h1 class="white-text center-align card-number">512</h1>
                </div>
            </div>
            <div class="col l3 s12 card-wrapper">
                <div class="card z-depth-3" style="background-color: #D41367;">
                    <h5 class="center-align white-text card-header">
                        Volunteer Hours
                    </h5>
                    <hr>
                    <h1 class="white-text center-align card-number">2560</h1>
                </div>
            </div>
        </div>
    </div>
</section> {% endcomment %}
<br><br>
</div>
{% endblock content%}

Main/templates/Main/m_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Rotaract</title>
        {% block description %}{% endblock %}
        <meta name="google-site-verification" content="iMTaFl6E5zCIsxlp0ocqGVKPqsKX8585i4pb44LPghE" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="{% static 'Main/images/district_logo.png' %}" type="image/icon type">

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
        
        <link rel="stylesheet" href="{% static 'Main/css/m_pages-d.css' %}">
        <link rel="stylesheet" href="{% static 'Main/css/m_pages-m.css' %}">
    </head>
    <main>
        <body id="body">
            {% include "Main/m_navbar.html" %}
            {% block content %}{% endblock %}
        </body>
    </main>
    
    {% include "Main/m_footer.html" %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'Main/javascript/init.js' %}"></script>
    <script>
        $(document).ready(function() {
            $("a").removeClass("active");
            $("#desktop-{{Tab}}").addClass("active");
            $("#mobile-{{Tab}}").addClass("active");
            $("#desktop-{{SubTab}}").addClass("pink-text");
            $("#mobile-{{SubTab}}").addClass("pink-text");
            $("div.input-field").click(function (e) {
            $(this).removeClass("ifb");
                e.stopPropagation();
            });
        });
    </script>
    {% block javascript %}{% endblock %}
</html>

Main/templates/Main/m_document.html
<!DOCTYPE html>
{% load static %}
<html lang="en">  
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Rotaract</title>
        <link rel="icon" href="{% static 'Main/images/district_logo.png' %}" type="image/icon type">

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Anton' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    </head>
    <body>
        <!-- <iframe id="iframepdf" src="{% static 'Main/images/council/shraddha.jpg' %}" style="height:100vh;width:100%"></iframe> -->
        {% if document == "0" %}
        <object data="{% static 'Main/resources/District Directory RIY 2020-21.pdf' %}" type="application/pdf" style="height:100vh;width:100%;">
            <embed src="{% static 'Main/resources/District Directory RIY 2020-21.pdf' %}" type="application/pdf" style="height:100vh;width:100%" />
        </object>
        {% elif document == "1" %}
        <object data="{% static 'Main/resources/Rotaract Handbook .pdf' %}" type="application/pdf" style="height:100vh;width:100%;">
            <embed src="{% static 'Main/resources/Rotaract Handbook .pdf' %}" type="application/pdf" style="height:100vh;width:100%" />
        </object>
        {% elif document == "2" %}
        <object data="{% static 'Main/resources/Rotaract Standard Constitution.pdf' %}" type="application/pdf" style="height:100vh;width:100%;">
            <embed src="{% static 'Main/resources/Rotaract Standard Constitution.pdf' %}" type="application/pdf" style="height:100vh;width:100%" />
        </object>
        {% elif document == "3" %}
        <object data="{% static 'Main/resources/Bylaws of Rotary International.pdf' %}" type="application/pdf" style="height:100vh;width:100%;">
            <embed src="{% static 'Main/resources/Bylaws of Rotary International.pdf' %}" type="application/pdf" style="height:100vh;width:100%" />
        </object>
        {% elif document == "4" %}
        <object data="{% static 'Main/resources/Constitution of Rotary International.pdf' %}" type="application/pdf" style="height:100vh;width:100%;">
            <embed src="{% static 'Main/resources/Constitution of Rotary International.pdf' %}" type="application/pdf" style="height:100vh;width:100%" />
        </object>
        {% elif document == "5" %}
        <object data="{% static 'Main/resources/Rotary Code of Policies.pdf' %}" type="application/pdf" style="height:100vh;width:100%;">
            <embed src="{% static 'Main/resources/Rotary Code of Policies.pdf' %}" type="application/pdf" style="height:100vh;width:100%" />
        </object>
        
        {% endif %}
    </body>
</html>

Main/templates/Main/m_headerSection.html
<section class="row flex header-section"> 
        <div class="col s12">
            <h3 class="center-align">{{text}}</h3>
            <hr>
        </div>
</section>

Main/templates/Main/m_loader.html
<section class="preLoader center-align" style="padding:10%;">
  <div class="preloader-wrapper active">
    <div class="spinner-layer">
      <div class="circle-clipper left">
        <div class="circle"></div>
      </div><div class="gap-patch">
        <div class="circle"></div>
      </div><div class="circle-clipper right">
        <div class="circle"></div>
      </div>
    </div>
  </div>
  <div id="quote">
      Good things take time ..
  </div>
</section>

Main/templates/Main/m_testWhatWeDo.html
{% extends "Main/m_base.html" %}

{% load static %}
{% block content %}
<style>
    #events .container {
        width:95%;padding-top:2%;
    }
    .instagram-media {
        max-width:100% !important;width:100% !important;min-width:100% !important;
    }
    hr {
        width:85%;border-width: 1px;border-color: black;background-color: black;margin-bottom:5%;margin-top:5%;
    }
    .eventName {
        line-height: 3rem; padding-bottom: 10px;
    }
    .eventCategory {
        padding-bottom: 10px;color:#3897f0;
    }
    @media screen and (max-width: 1000px) {
        hr {
            width:40%;
            margin-top:10%;
            margin-bottom:10%;
        }
        h4 {
            font-size: 2.3em;
            
        }
        .instagram-media {
            margin-top:15% !important;
        }
        .eventInformation {
            padding:0%;
            margin:0%;
        }
    }
    @media screen and (min-width: 1000px) {
        .eventInformation {
            padding-right:6% !important;
        }
        
    }
</style>
<section class="section hideAll" id="events">
    <div class="container">
    {% for event in events %}
        <div class="row flex">
            <div class="col s12 l9 m12 eventInformation">
                <h4 class="eventName"><b>{{event.eventName}}</b></h4>
                <h6 class="eventCategory">A {{event.get_eventCategory_display}} Project</h6>
                <p class="eventDescription">
                    {{event.eventDescription |safe}}
                </p>
            </div>
            <div class="col s12 l3 m12">
                <div>
                    {{event.eventInstagramPost |safe}}
                </div>
            </div>
        </div>
        {% ifnotequal forloop.counter events.count %}
            <hr>
        {% endifnotequal %}
    {% endfor %}
    </div>
</section>
{% include "Main/m_loader.html" %}
{% endblock content%}

{% block javascript %}

<script>
    var mq = window.matchMedia("(max-width: 1000px)");
    if (mq.matches) {
        $('.row').removeClass('flex');
        $('h4').addClass("center-align");
        $('h6').addClass("center-align");
    }
</script>

{% endblock %}